"""initial tables

Revision ID: 35d4b495be2c
Revises: a1b2c3d4e5f6
Create Date: 2026-07-01 22:37:05.002926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35d4b495be2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ats_results', schema=None) as batch_op:
        batch_op.alter_column('missing_sections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('missing_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_ats_job_description'))
        batch_op.drop_index(batch_op.f('ix_ats_results_analysis_id'))
        batch_op.drop_constraint(batch_op.f('fk_ats_job_description'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ats_analysis'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_descriptions', ['job_description_id'], ['id'])
        batch_op.create_foreign_key(None, 'resume_analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_chatbot_conversations_user'))

    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_chatbot_messages_conversation'))
        batch_op.drop_index(batch_op.f('idx_chatbot_messages_timestamp'))

    with op.batch_alter_table('comparison_resumes', schema=None) as batch_op:
        batch_op.alter_column('resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_compare_resume'), type_='foreignkey')

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cover_letters_created_at'))
        batch_op.drop_index(batch_op.f('idx_cover_letters_job_desc'))
        batch_op.drop_index(batch_op.f('idx_cover_letters_resume'))
        batch_op.drop_index(batch_op.f('idx_cover_letters_user'))

    with op.batch_alter_table('cv_draft_sections', schema=None) as batch_op:
        batch_op.alter_column('section_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_cv_draft_sections_draft_id'))
        batch_op.drop_constraint(batch_op.f('cv_draft_sections_draft_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cv_drafts', ['draft_id'], ['id'])

    with op.batch_alter_table('cv_drafts', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'template'::text"))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
        batch_op.drop_index(batch_op.f('ix_cv_drafts_user_id'))

    with op.batch_alter_table('generated_cvs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_cvs_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_generated_cvs_user_id'))

    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jd_user'))
        batch_op.drop_constraint(batch_op.f('fk_jd_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_recommendations_analysis_id'))
        batch_op.drop_constraint(batch_op.f('fk_recommendation_analysis'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_recommendation_section'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'resume_sections', ['section_id'], ['id'])
        batch_op.create_foreign_key(None, 'resume_analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.alter_column('major',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_analysis_resume'))
        batch_op.drop_index(batch_op.f('idx_analysis_user'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_user_created'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_analysis_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_analysis_resume'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('resume_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comparison_user'))
        batch_op.drop_constraint(batch_op.f('fk_comparison_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_sections_resume_id'))
        batch_op.drop_constraint(batch_op.f('fk_section_resume'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('parsed_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_resumes_user'))
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_resume_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_verification_token_key'), type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token_expires_at')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_verification_token_key'), ['verification_token'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_resume_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_resumes_user'), ['user_id'], unique=False)
        batch_op.alter_column('parsed_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_section_resume'), 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_resume_sections_resume_id'), ['resume_id'], unique=False)

    with op.batch_alter_table('resume_comparisons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comparison_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_comparison_user'), ['user_id'], unique=False)

    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_analysis_resume'), 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_analysis_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_resume_analyses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_user_created'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_resume'), ['resume_id'], unique=False)
        batch_op.alter_column('major',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recommendation_section'), 'resume_sections', ['section_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_recommendation_analysis'), 'resume_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_recommendations_analysis_id'), ['analysis_id'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jd_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_jd_user'), ['user_id'], unique=False)

    with op.batch_alter_table('generated_cvs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_cvs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_cvs_analysis_id'), ['analysis_id'], unique=False)

    with op.batch_alter_table('cv_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_drafts_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
        batch_op.alter_column('mode',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'template'::text"))

    with op.batch_alter_table('cv_draft_sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cv_draft_sections_draft_id_fkey'), 'cv_drafts', ['draft_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_cv_draft_sections_draft_id'), ['draft_id'], unique=False)
        batch_op.alter_column('section_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cover_letters_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cover_letters_resume'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cover_letters_job_desc'), ['job_description_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cover_letters_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('comparison_resumes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_compare_resume'), 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chatbot_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_chatbot_messages_conversation'), ['conversation_id'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chatbot_conversations_user'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('ats_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ats_analysis'), 'resume_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_ats_job_description'), 'job_descriptions', ['job_description_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_ats_results_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ats_job_description'), ['job_description_id'], unique=False)
        batch_op.alter_column('missing_keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('missing_sections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
